### ISSUE TITLE
Request for Access to the ExtraVul Dataset

### ISSUE THREAD

**Issue by Ringbo** [tuhh-softsec/APR4Vul#1]
Hi, thank you for your inspiring study. I am interested in the ExtraVul dataset. 
Could you provide this dataset or a script to extract the vulnerabilities from Project KB? Many thanks.

**Comment by bqcuong** [comment]
Hi,

Thanks for your interest.
You can find the information about ExtraVul in this repository, at `evaluation_data/RQ3 - ExtraVul Repair Actions and Repair Patterns Analyses.xlsx`.

Cheers,
Cuong

**Comment by Ringbo** [comment]
Great! Many thanks!
